export interface Specialist {
  slug: string;
  name: string;
  nameAccusative?: string;
  feminine?: boolean;
  initials: string;
  photo: string | null;
  role: string;
  roleEn: string;
  tagline: string;
  taglineEn: string;
  about: string[];
  aboutEn: string[];
  conditions?: string[];
  conditionsEn?: string[];
  expertise: string[];
  expertiseEn: string[];
  education: string[];
  educationEn: string[];
  license?: string;
  languages?: string[];
  courses?: string[];
  coursesEn?: string[];
}

export const specialists: Specialist[] = [
  {
    slug: "piotr-dubrovskij",
    name: "Piotr Dubrovskij",
    nameAccusative: "Piotrą",
    initials: "PD",
    photo: "/specialist-piotr.jpg",
    role: "Kineziterapeutas, osteopatas, manualinės terapijos specialistas",
    roleEn: "Physiotherapist, osteopath, manual therapy specialist",
    tagline: "Stuburo ir kaklo problemos, sudėtingesnės judamojo aparato būklės, osteopatija",
    taglineEn: "Spine and neck problems, complex musculoskeletal conditions, osteopathy",
    about: [
      "Piotr Dubrovskij – patyręs kineziterapeutas, osteopatas ir manualinės terapijos specialistas, dirbantis su įvairiais judamojo aparato sutrikimais – nuo stuburo ir kaklo skausmų iki sudėtingesnių funkcinių bei pooperacinių būklių.",
      "Savo darbe jis taiko integruotą požiūrį, derindamas kineziterapiją, manualinę terapiją, osteopatinius principus ir kitus individualiai parinktus metodus. Gydymo tikslas – ne tik sumažinti simptomus, bet ir nustatyti problemos priežastis, atkurti judesio kokybę bei padėti pacientui grįžti į visavertį kasdienį gyvenimą.",
      "Piotr taip pat turi ilgametę patirtį sporto medicinos srityje. Nuo 2012 m. jis yra Lietuvos nacionalinės ir jaunimo ledo ritulio rinktinių vyr. kineziterapeutas, o nuo 2020 m. dėsto Vilniaus universiteto Medicinos fakulteto Reabilitacijos, fizinės ir sporto medicinos katedroje. Ši patirtis leidžia jam efektyviai dirbti tiek su sportininkais, tiek su pacientais, susiduriančiais su sudėtingesnėmis judamojo aparato problemomis.",
    ],
    aboutEn: [
      "Piotr Dubrovskij is an experienced physiotherapist, osteopath and manual therapy specialist working with a wide range of musculoskeletal disorders — from spinal and neck pain to more complex functional and post-surgical conditions.",
      "He applies an integrated approach, combining physiotherapy, manual therapy, osteopathic principles and other individually selected methods. The goal of treatment is not only to reduce symptoms, but to identify the causes of the problem, restore movement quality and help the patient return to full daily life.",
      "Piotr also has extensive experience in sports medicine. Since 2012 he has been the head physiotherapist of the Lithuanian National and Youth Ice Hockey Teams, and since 2020 he has been teaching at the Department of Rehabilitation, Physical and Sports Medicine at Vilnius University Faculty of Medicine. This experience allows him to work effectively both with athletes and patients facing more complex musculoskeletal problems.",
    ],
    conditions: [
      "Stuburo ir kaklo skausmai",
      "Nervų dirginimo simptomai",
      "Sudėtingesni judamojo aparato sutrikimai",
      "Pooperacinis atsistatymas",
      "Ūmios ir lėtinės skausmo būklės",
      "Funkciniai judėjimo sutrikimai",
      "Sportinės traumos ir grįžimas į krūvį",
      "Pasikartojančių problemų prevencija",
    ],
    conditionsEn: [
      "Spinal and neck pain",
      "Nerve irritation symptoms",
      "Complex musculoskeletal disorders",
      "Post-surgical recovery",
      "Acute and chronic pain conditions",
      "Functional movement disorders",
      "Sports injuries and return to load",
      "Prevention of recurring problems",
    ],
    expertise: [
      "Kineziterapija",
      "Manualinė terapija",
      "Osteopatija",
      "Kraniosakralinė terapija",
      "Visceralinė manipuliacija",
      "Dinaminė neuromuskulinė stabilizacija (DNS)",
      "Sausų adatų terapija",
      "Individualus funkcinio atsistatymo planas",
    ],
    expertiseEn: [
      "Physiotherapy",
      "Manual therapy",
      "Osteopathy",
      "Craniosacral therapy",
      "Visceral manipulation",
      "Dynamic neuromuscular stabilisation (DNS)",
      "Dry needling",
      "Individual functional recovery plan",
    ],
    license: "ASL-13170",
    languages: ["Lietuvių", "Rusų", "Anglų"],
    education: [
      "2011–2013 · Reabilitacijos magistrantūra, Vilniaus universiteto Medicinos fakultetas",
      "2010 · Išlyginamosios kineziterapijos studijos, Vilniaus universiteto Medicinos fakultetas",
      "2007–2010 · Kineziterapijos bakalauras, Vilniaus kolegija, Sveikatos priežiūros fakultetas",
    ],
    educationEn: [
      "2011–2013 · Master's in Rehabilitation, Vilnius University Faculty of Medicine",
      "2010 · Supplementary physiotherapy studies, Vilnius University Faculty of Medicine",
      "2007–2010 · Bachelor's in Physiotherapy, Vilnius College, Faculty of Health Care",
    ],
    courses: [
      '2012–2014|International College of Applied Kinesiology|',
      '2014–2016|European School of Osteopathy|',
      '2018|The Upledger Institute: CS1 – kraniosakralinė terapija|',
      '2018|The Upledger Institute: CS2 – kraniosakralinė terapija|',
      '2018|Manual Concepts – Spinal Manual Therapy. Nugaros manualinė terapija|',
      '2019|Visceral Manipulation, Abdomen 1 (VM1)|',
      '2020|Visceral Manipulation, Abdomen 2 (VM2)|',
      '2021|Visceral Manipulation, The Thorax (VM4)|',
      '2021|Neural Manipulation: Neuromeningeal Manipulation – NM1|',
      '2021|New Manual Articular Approach – Spine and Pelvis (MASP)|',
      '2021|DNS Pediatric course 1|',
      '2022|DNS Pediatric course 2|',
      '2021|DNS Pediatric course 3|',
      '2022|Fascial Manipulation Stecco, Level 1 Course|',
      '2022|Dry Needling Certification Course Level 1 & 2 (Craig Smith). Akupunktūra: jungiamojo audinio ir raumeninė technika|',
    ],
    coursesEn: [
      '2012–2014|International College of Applied Kinesiology|',
      '2014–2016|European School of Osteopathy|',
      '2018|The Upledger Institute: CS1 – Craniosacral therapy|',
      '2018|The Upledger Institute: CS2 – Craniosacral therapy|',
      '2018|Manual Concepts – Spinal Manual Therapy|',
      '2019|Visceral Manipulation, Abdomen 1 (VM1)|',
      '2020|Visceral Manipulation, Abdomen 2 (VM2)|',
      '2021|Visceral Manipulation, The Thorax (VM4)|',
      '2021|Neural Manipulation: Neuromeningeal Manipulation – NM1|',
      '2021|New Manual Articular Approach – Spine and Pelvis (MASP)|',
      '2021|DNS Pediatric course 1|',
      '2022|DNS Pediatric course 2|',
      '2021|DNS Pediatric course 3|',
      '2022|Fascial Manipulation Stecco, Level 1 Course|',
      '2022|Dry Needling Certification Course Level 1 & 2 (Craig Smith)|',
    ],
  },
  {
    slug: "kotryna-kairyte",
    name: "Kotryna Kairytė",
    nameAccusative: "Kotryną",
    feminine: true,
    initials: "KK",
    photo: "/specialist-kotryna.jpg",
    role: "Kineziterapeutė",
    roleEn: "Physiotherapist",
    tagline: "Sporto traumos, ortopedinės problemos, grįžimas į sportą",
    taglineEn: "Sports injuries, orthopaedic problems, return to sport",
    about: [
      "Kotryna Kairytė – kineziterapeutė, besispecializuojanti sporto traumų reabilitacijoje, ortopedinių problemų gydyme ir saugiame grįžime į aktyvų gyvenimą bei sportą.",
      "Savo darbe ji derina šiuolaikinius reabilitacijos principus, individualų krūvio parinkimą ir funkcinio atsistatymo metodus, padedančius pacientui nuosekliai atkurti judėjimo kokybę, sumažinti skausmą ir grįžti prie įprasto fizinio aktyvumo.",
      "Kotryna turi praktinės patirties dirbant su aukšto meistriškumo sportininkais. Nuo 2022 m. ji yra Lietuvos nacionalinės moterų futbolo rinktinės kineziterapeutė, o nuo 2019 m. dirba su Lietuvos nacionaline ir jaunimo ledo ritulio rinktinėmis. Ši patirtis leidžia jai efektyviai dirbti tiek su sportininkais, tiek su aktyvų gyvenimo būdą mėgstančiais pacientais.",
    ],
    aboutEn: [
      "Kotryna Kairytė is a physiotherapist specialising in sports injury rehabilitation, orthopaedic problem treatment and safe return to active life and sport.",
      "She combines modern rehabilitation principles, individual load selection and functional recovery methods to help patients systematically restore movement quality, reduce pain and return to their normal physical activity.",
      "Kotryna has practical experience working with high-performance athletes. Since 2022 she has been the physiotherapist of the Lithuanian Women's National Football Team, and since 2019 she has worked with the Lithuanian National and Youth Ice Hockey Teams. This experience allows her to work effectively both with athletes and patients who lead an active lifestyle.",
    ],
    conditions: [
      "Sporto traumos",
      "Ortopedinės problemos",
      "Kelio ir peties sutrikimai",
      "Perkrovų sindromai",
      "Skausmas fizinio aktyvumo metu",
      "Atsistatymas po traumų",
      "Pooperacinė reabilitacija",
      "Grįžimas į sportą",
    ],
    conditionsEn: [
      "Sports injuries",
      "Orthopaedic problems",
      "Knee and shoulder conditions",
      "Overuse syndromes",
      "Pain during physical activity",
      "Recovery after injuries",
      "Post-surgical rehabilitation",
      "Return to sport",
    ],
    expertise: [
      "Kineziterapija",
      "Sporto reabilitacija",
      "Funkcinio atsistatymo planavimas",
      "Krūvio dozavimas",
      "Judesio vertinimas",
      "Individualus grįžimo į sportą planas",
    ],
    expertiseEn: [
      "Physiotherapy",
      "Sports rehabilitation",
      "Functional recovery planning",
      "Load management",
      "Movement assessment",
      "Individual return-to-sport plan",
    ],
    license: "ASL-04527",
    languages: ["Lietuvių", "Anglų", "Rusų"],
    education: [
      "2023 · Sporto kineziterapijos magistras, Lietuvos sveikatos mokslų universitetas",
      "2021 · Kineziterapijos bakalauras, Vilniaus universitetas",
    ],
    educationEn: [
      "2023 · Master's in Sports Physiotherapy, Lithuanian University of Health Sciences",
      "2021 · Bachelor's in Physiotherapy, Vilnius University",
    ],
    courses: [
      '2019.05|Kineziologinio teipavimo pagrindai ir taikymas reabilitacijoje|',
      '2019.10|Viršutinių galūnių sportinių traumų diagnostika, gydymas ir kineziterapija|',
      '2019.11|Apatinių galūnių sportinių traumų diagnostika, gydymas ir kineziterapija|',
      '2020.06|Smūginių (akustinių) bangų terapija|',
      '2020.06|Dubens ištyrimas ir kineziterapija|',
      '2020.09|Funkcinio mobilumo treniravimas|',
      '2020.11|Ateities sporto mokslas: moksliniais įrodymais pagrįsta sporto praktika ir medicina|',
      '2021.10|Mulligan manualinės terapijos koncepcija: viršutinis ir apatinis kvadrantas|',
      '2022|Metinis atletinio rengimo planas|',
      '2023|Krūvių dozavimas sporte ir reabilitacijoje|',
      '2023|Šiuolaikinė elektroterapija reabilitacijoje ir sporte|',
      '2023|International conference: We are not ready for the joint replacement|',
    ],
    coursesEn: [
      '2019.05|Fundamentals of kinesiology taping and application in rehabilitation|',
      '2019.10|Diagnostics, treatment and physiotherapy of upper limb sports injuries|',
      '2019.11|Diagnostics, treatment and physiotherapy of lower limb sports injuries|',
      '2020.06|Shock (acoustic) wave therapy|',
      '2020.06|Pelvic assessment and physiotherapy|',
      '2020.09|Functional mobility training|',
      '2020.11|Future sports science: evidence-based sports practice and medicine|',
      '2021.10|Mulligan manual therapy concept: upper and lower quadrant|',
      '2022|Annual athletic training plan|',
      '2023|Load management in sport and rehabilitation|',
      '2023|Modern electrotherapy in rehabilitation and sport|',
      '2023|International conference: We are not ready for the joint replacement|',
    ],
  },
  {
    slug: "erikas-jatkauskas",
    name: "Erikas Jatkauskas",
    nameAccusative: "Eriką",
    initials: "EJ",
    photo: "/specialist-erikas.jpg",
    role: "Kineziterapeutas",
    roleEn: "Physiotherapist",
    tagline: "Kasdienio judamojo aparato problemos, skausmo mažinimas, funkcijos atkūrimas",
    taglineEn: "Everyday musculoskeletal problems, pain relief, function restoration",
    about: [
      "Erikas Jatkauskas – kineziterapeutas, dirbantis su įvairiomis judamojo aparato problemomis – nuo ūmių skausmų iki lėtinių perkrovos sindromų ir funkcinių sutrikimų.",
      "Savo darbe jis orientuojasi į aiškų problemos įvertinimą, skausmo mažinimą ir ilgalaikį funkcijos atkūrimą. Kiekvienam pacientui taiko individualų požiūrį, parinkdamas tinkamiausius metodus pagal būklę, fizinį pasirengimą ir kasdienius poreikius.",
      "Erikas taip pat dirba su sportuojančiais pacientais ir nuo 2022 m. yra Lietuvos jaunimo ledo ritulio rinktinės kineziterapeutas. Praktinė patirtis sporto aplinkoje padeda jam efektyviai taikyti reabilitacijos principus tiek aktyviai sportuojantiems, tiek kasdienius judėjimo sutrikimus patiriantiems pacientams.",
    ],
    aboutEn: [
      "Erikas Jatkauskas is a physiotherapist working with a wide range of musculoskeletal problems — from acute pain to chronic overuse syndromes and functional disorders.",
      "He focuses on clear problem assessment, pain reduction and long-term function restoration. He applies an individual approach for each patient, selecting the most appropriate methods according to the condition, fitness level and daily needs.",
      "Erikas also works with athletes and has been the physiotherapist of the Lithuanian Youth Ice Hockey National Team since 2022. His practical experience in the sports environment helps him effectively apply rehabilitation principles both to active athletes and patients with everyday movement disorders.",
    ],
    conditions: [
      "Nugaros ir kaklo skausmai",
      "Sąnarių skausmai ir judesių ribotumas",
      "Raumenų perkrova ir įtampos sindromai",
      "Sportinės traumos ir atsistatymas po jų",
      "Funkciniai judėjimo sutrikimai",
      "Kasdienio fizinio krūvio sukeltos problemos",
      "Skausmo mažinimas ir judėjimo kokybės gerinimas",
    ],
    conditionsEn: [
      "Back and neck pain",
      "Joint pain and restricted movement",
      "Muscle overuse and tension syndromes",
      "Sports injuries and recovery",
      "Functional movement disorders",
      "Problems caused by daily physical load",
      "Pain reduction and movement quality improvement",
    ],
    expertise: [
      "Kineziterapija",
      "Skausmo mažinimas",
      "Funkcinis atsistatymas",
      "Sąnarių problemos",
      "Raumenų sutrikimai",
      "Sporto kineziterapija",
      "Traumų prevencija",
      "Reabilitacija po fizinės perkrovos",
    ],
    expertiseEn: [
      "Physiotherapy",
      "Pain reduction",
      "Functional recovery",
      "Joint problems",
      "Muscle disorders",
      "Sports physiotherapy",
      "Injury prevention",
      "Rehabilitation after physical overload",
    ],
    license: "ASL-14117",
    languages: ["Lietuvių", "Anglų"],
    education: [
      "2021–2024 · Kineziterapijos bakalauro studijos, Vilniaus universitetas, Medicinos fakultetas",
    ],
    educationEn: [
      "2021–2024 · Bachelor's studies in Physiotherapy, Vilnius University, Faculty of Medicine",
    ],
    courses: [
      '2022.10.12|Klinikinė patirtis dirbant su aukšto meistriškumo sportininkais. Fizinis ir emocinis sportininko pasiruošimas prieš varžybas|',
      '2022.10.27|Peties kineziologija ir funkcinė anatomija|',
      '2022.09.27|Apatinių galūnių traumos|',
      '2022.11.11|Maitland workshop|',
      '2023.04.19|Kelio sąnario problemos|',
      '2023.05.09|Klinikinė kineziologija ir funkcinė anatomija: viršutinė galūnė – alkūnė, riešas|',
      '2023.05.23|Viršutinių galūnių traumos, testavimas ir prevencija|',
      '2023.06.08|Skoliozė: nuo gairių iki praktikos|',
    ],
    coursesEn: [
      '2022.10.12|Clinical experience working with high-performance athletes. Physical and emotional preparation before competitions|',
      '2022.10.27|Shoulder kinesiology and functional anatomy|',
      '2022.09.27|Lower limb injuries|',
      '2022.11.11|Maitland workshop|',
      '2023.04.19|Knee joint problems|',
      '2023.05.09|Clinical kinesiology and functional anatomy: upper limb – elbow, wrist|',
      '2023.05.23|Upper limb injuries, testing and prevention|',
      '2023.06.08|Scoliosis: from guidelines to practice|',
    ],
  },
  {
    slug: "mangirdas-kazacenko",
    name: "Mangirdas Kazačenko",
    nameAccusative: "Mangirdą",
    initials: "MK",
    photo: "/specialist-mangirdas.jpg",
    role: "Kineziterapeutas, manualinės terapijos specialistas, masažuotojas",
    roleEn: "Physiotherapist, manual therapy specialist, massage therapist",
    tagline: "Nugaros, kaklo ir sąnarių skausmai, manualinė terapija, funkcinis atsistatymas",
    taglineEn: "Back, neck and joint pain, manual therapy, functional recovery",
    about: [
      "Mangirdas Kazačenko – kineziterapeutas, manualinės terapijos specialistas ir masažuotojas, dirbantis su pacientais, turinčiais įvairių griaučių-raumenų sistemos sutrikimų.",
      "Savo darbe jis taiko individualų ir integruotą požiūrį, siekdamas ne tik sumažinti simptomus, bet ir padėti pacientui kuo greičiau bei saugiau grįžti į visavertį kasdienį gyvenimą.",
      "Atsižvelgdamas į paciento būklę ir poreikius, Mangirdas taiko kineziterapiją, manualinę terapiją, gydomąjį masažą, fizioterapines priemones, o tam tikrais atvejais – ir papildomus skausmo valdymo sprendimus.",
    ],
    aboutEn: [
      "Mangirdas Kazačenko is a physiotherapist, manual therapy specialist and massage therapist working with patients with various musculoskeletal disorders.",
      "He applies an individual and integrated approach, aiming not only to reduce symptoms but to help patients return to full daily life as quickly and safely as possible.",
      "Depending on the patient's condition and needs, Mangirdas uses physiotherapy, manual therapy, therapeutic massage, physiotherapy modalities, and in certain cases additional pain management solutions.",
    ],
    conditions: [
      "Nugaros skausmas",
      "Kaklo skausmas ir įtampa",
      "Sąnarių judesių apribojimai",
      "Raumenų ir fascijų įtampos",
      "Potrauminis atsistatymas",
      "Funkciniai judėjimo sutrikimai",
      "Pasikartojančių skausmų prevencija",
      "Sportinių traumų reabilitacija",
    ],
    conditionsEn: [
      "Back pain",
      "Neck pain and tension",
      "Restricted joint movement",
      "Muscle and fascial tension",
      "Post-traumatic recovery",
      "Functional movement disorders",
      "Recurring pain prevention",
      "Sports injury rehabilitation",
    ],
    expertise: [
      "Kineziterapija",
      "Manualinė terapija (Maitland)",
      "Gydomasis masažas",
      "Sąnarių mobilizacija",
      "Fizioterapinės priemonės",
      "Sporto kineziterapija ir traumų prevencija",
      "Kasdienės ergonomikos sprendimai",
    ],
    expertiseEn: [
      "Physiotherapy",
      "Manual therapy (Maitland)",
      "Therapeutic massage",
      "Joint mobilisation",
      "Physiotherapy modalities",
      "Sports physiotherapy and injury prevention",
      "Everyday ergonomics solutions",
    ],
    license: "ASL-06701",
    languages: ["Lietuvių", "Anglų", "Rusų"],
    education: [
      "2018 – Kineziterapijos profesinio bakalauro laipsnis, kineziterapeuto kvalifikacija",
    ],
    educationEn: [
      "2018 – Professional Bachelor's degree in Physiotherapy",
    ],
    courses: [
      '2018|Masažo pagrindai (masažuotojo spaudai)|Vilniaus kolegija',
      '2019|Stuburo degeneracinės ligos – funkcinė anatomija, reabilitacija, slauga|VšĮ RVUL',
      '2019|Maitland manualinė terapija – 1 lygis|UAB Kineziterapijos klinika',
      '2019|Galvos smegenų arterijų aneurizma – anatomija, klinika, reabilitacija, slauga|VšĮ RVUL',
      '2022|We are not ready for the joint replacement|LSMU',
      '2024|Maitland manualinė terapija – 2A lygis|UAB Kineziterapijos klinika',
      '2025|Maitland manualinė terapija – 2B lygis|UAB Kineziterapijos klinika',
      '2025|Muskuloskeletinė radiologinė diagnostika: teorija ir praktika|UAB Kineziterapijos klinika',
      '2026 sausis|Klinikinė hipnozė skausmo valdymui (pagal Giancarlo Russo)|Smart Moves Academy',
      '2026 sausis|Professional Cupping Therapy Course|Mark Perren-Jones',
      '2026 vasaris|Sausos adatos terapija (dry needling) TOP30 raumenų|David G. Simons akademija, Šveicarija',
    ],
    coursesEn: [
      '2018|Massage Fundamentals (pressure massage)|Vilnius College',
      '2019|Degenerative Spinal Diseases – Functional Anatomy, Rehabilitation, Nursing|VšĮ RVUL',
      '2019|Maitland Manual Therapy – Level 1|UAB Kineziterapijos klinika',
      '2019|Cerebral Artery Aneurysm – Anatomy, Clinic, Rehabilitation, Nursing|VšĮ RVUL',
      '2022|We are not ready for the joint replacement|LSMU',
      '2024|Maitland Manual Therapy – Level 2A|UAB Kineziterapijos klinika',
      '2025|Maitland Manual Therapy – Level 2B|UAB Kineziterapijos klinika',
      '2025|Musculoskeletal Radiological Diagnostics: Theory and Practice|UAB Kineziterapijos klinika',
      '2026 Jan|Clinical Hypnosis for Pain Management (by Giancarlo Russo)|Smart Moves Academy',
      '2026 Jan|Professional Cupping Therapy Course|Mark Perren-Jones',
      '2026 Feb|Dry Needling TOP30 muscles|David G. Simons Academy, Switzerland',
    ],
  },
];

export function getSpecialistBySlug(slug: string): Specialist | undefined {
  return specialists.find((s) => s.slug === slug);
}
